function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 02-Oct-2023 13:49:01

% Create figure
figure('WindowState','maximized');

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',3,'Color',[0 0 0]);
hold on
plot2 = plot(X1, zeros(length(X1),1), 'k', 'LineWidth', 3);
set(plot2,'LineStyle',':');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1.25 2.25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-4.50510855683269 17.1743295019157]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'LineWidth',2);
